import Bloglist from "@/Components/bloglist";
import Category from "@/Components/Category";
import Head from "next/head";

export default function Blog() {
  return (
    <>
    <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
   
          <Bloglist/>     
    
    </>
  );
}