import Head from "next/head";

export default function Contact() {
  return (
    <div>
       <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
     </Head>
     <div className="w3l-contact-breadcrumb w3l-search-results py-5 text-center">
    <div className="container py-lg-4 py-md-3">
        <h3 className="title-big mb-4">Contact Us</h3>
        <p>We want to provide you with a great experience which is why we want to hear from you. Your feedback helps us
            bring you more of the events you love and the service you expect.</p>
    </div>
    </div>
    </div>
  );
}