import Head from 'next/head'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer'
import Navbar from '@/Components/Navbar'
import Herosection from '@/Components/Herosection'
import Homebloglist from '@/Components/Homebloglist'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Dev Safari</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Herosection/>
      <Homebloglist/>
    </>
  )
}
